# Generated by Django 3.2 on 2023-09-07 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SESEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField()),
                ('message_subject', models.CharField(blank=True, max_length=5000)),
                ('event_type', models.CharField(max_length=50)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('resolved', 'Resolved')], default='new', max_length=50)),
            ],
        ),
    ]
